// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXWGf6znWgDd5c4S2J_Nwvc-4VaTfNEDs',
    appId: '1:782601409437:android:1129c38a7df92fdaf01574',
    messagingSenderId: '782601409437',
    projectId: 'fir-1-674c0',
    storageBucket: 'fir-1-674c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbX28XpJwFEsAqv10JqCO3LX4adARCP8',
    appId: '1:782601409437:ios:5edf8dfed02a9a5ff01574',
    messagingSenderId: '782601409437',
    projectId: 'fir-1-674c0',
    storageBucket: 'fir-1-674c0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClass1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfrIat3b0WAewTRuB6nsZm_NvAasJJ0Xw',
    appId: '1:782601409437:web:c9b648b1ee9da4e6f01574',
    messagingSenderId: '782601409437',
    projectId: 'fir-1-674c0',
    authDomain: 'fir-1-674c0.firebaseapp.com',
    storageBucket: 'fir-1-674c0.firebasestorage.app',
    measurementId: 'G-JPVL67932J',
  );
}
